version: '3.9'

services:
  frontend:
    container_name: softeo_frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t"]
      timeout: 10s
      retries: 5

  backend:
    container_name: softeo_backend
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=database
      - DB_NAME=ericas_clinic
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t"]
      timeout: 10s
      retries: 5
  
  database:
    image: mysql:8.0.21
    container_name: softeo_database
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
